server:
  port: 9191

spring:
  application:
    name: RETAIL-STORE-API-GATEWAY



  ##GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      routes:
        ## CART SERVICE
        - id: -CART-SERVICE
          uri: lb://CART-SERVICE
          predicates:
              - Path=/Cart/**
          #filters:            #- name: CircuitBreaker
              #args:                #name: CART-SERVICE
                #fallbackuri: forward:/cartserviceFallback
          
        ## COMPOSITE SERVICE
        - id: -COMPOSITE-SERVICE
          uri: lb://COMPOSITE-SERVICE
          predicates:
            - Path=/RetailStore/**
          #filters:
            #- name: CircuitBreaker
              #args:
                #name: COMPOSITE-SERVICE
                #fallbackuri: forward:/compositeserviceFallback
        ## CUSTOMER SERVICE
        - id: -CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/Customer/**
          #filters:
            #- name: CircuitBreaker
              #args:
                #name: CUSTOMER-SERVICE
                #fallbackuri: forward:/customerserviceFallback
        ## INVENTORY SERVICE
        - id: -INVENTORY-SERVICE
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/Inventory/**
          #filters:
            #- name: CircuitBreaker
              #args:
                #name: INVENTORY-SERVICE
                #fallbackuri: forward:/inventoryserviceFallback
        ## ORDER SERVICE
        - id: -ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/Order/**
          #filters:
          #- name: CircuitBreaker
            #args:
              #name: ORDER-SERVICE
              #fallbackuri: forward:/orderserviceFallback
        ## PRODUCT SERVICE
        - id: -PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/Product/**
          #filters:
          #- name: CircuitBreaker
            #args:
              #name: PRODUCT-SERVICE
              #fallbackuri: forward:/productserviceFallback
          
        
#hystrix:
 # command:
 #   fallbackcmd:
 #     execution:
 #       isolation:
 #         thread:
 #           timeoutInMilliseconds: 4000         
          

#management:#  endpoints:#    web:#      exposure:#        include: hystrix.stream















 
